### ISSUE TITLE
BadgerDB logger seems to be broken in latest update

### ISSUE THREAD

**Issue by nmarley** [aergoio/aergo-lib#3]
Hi, It seems like the latest update of Aergo-lib doesn't allow for BadgerDB instance to be created. Specifically, I can't create a BadgerDB instance without the lib `panic`ing. This didn't happen in the previous version (v1.3.0).

I have a minimal code example to demonstrate this panic:

```go
package main

import (
	"log"

	"github.com/aergoio/aergo-lib/db"
)

func main() {
	aergoDB, err := db.NewBadgerDB("data")
	if err != nil {
		log.Fatal(err)
	}
	defer aergoDB.Close()
}
```

Here is the panic that is generated:

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1562c12]

goroutine 1 [running]:
github.com/aergoio/aergo-lib/db.(*extendedLog).Infof(0x0, 0x16b2307, 0x1b, 0xc0054c4080, 0x2, 0x2)
	/Users/nmarley/go/pkg/mod/github.com/aergoio/aergo-lib@v0.0.0-20191115072213-6103468b06ac/db/logger.go:24 +0x22
github.com/dgraph-io/badger.(*Options).Infof(...)
	/Users/nmarley/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/logger.go:46
github.com/dgraph-io/badger.newLevelsController(0xc00016c000, 0xc00010fa98, 0x0, 0x0, 0x0)
	/Users/nmarley/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/levels.go:175 +0xe56
github.com/dgraph-io/badger.Open(0x16a3d70, 0x4, 0x16a3d70, 0x4, 0x1, 0x0, 0x0, 0x1, 0x0, 0x17886e0, ...)
	/Users/nmarley/go/pkg/mod/github.com/dgraph-io/badger@v1.6.0/db.go:288 +0xb75
github.com/aergoio/aergo-lib/db.NewBadgerDB(0x16a3d70, 0x4, 0x16a755c, 0x8, 0xc00012ca58, 0xc000123f20)
	/Users/nmarley/go/pkg/mod/github.com/aergoio/aergo-lib@v0.0.0-20191115072213-6103468b06ac/db/badgerdb.go:96 +0x136
main.main()
	/Users/nmarley/projects/aergo-db-log-broken/main.go:10 +0x48
exit status 2
```

If it helps, the contents of the `data` dir after this panic is just a single file `MANIFEST`.

I believe this is probably related to the replacement of the badger default logger in https://github.com/aergoio/aergo-lib/commit/edf758fca70b7afae866d84b2dfaeaabb1687f09, but I am currently not too familiar with the lib. Am I using this wrong (e.g. API changed), or does this look like a legitimate bug?

Thanks,

**Comment by hanlsin** [comment]
Thanks, @nmarley.

We will try to fix it asap. :)

**Comment by sunpuyo** [comment]
Hi @nmarley. Thank you for reporting.
We recommend to create new db like this in aergo.
`db.NewDB(db.BadgerImpl, dbPath)`

however it can be used like that... so i will fix it

**Comment by nmarley** [comment]
Ok, thank you! This is working now using the NewDB constructor. It also fixes an issue I saw with the BadgerDB garbage collector.

For ` NewDB`, I noticed that it panics if the DB can't be created. Was this an intentional design decision or would it be better to pass the error thru? Thanks.

**Comment by sunpuyo** [comment]
Creating each DB directly is unintentional, so we changed it to private. I'm sorry that the interface has changed accordingly. Check the next commit
https://github.com/aergoio/aergo-lib/commit/7beb96d31892b53e0d4997931c84188ec97090c0
